# These are custom settings (also for hardware interface).
# Please modify these values to fit your robot.
# =========== Custom setting start ===========
robot:
    n_dof: 2
    update_freq: 10
    control_type: vp # Choose one of these: [pp, pv, vp, vv, fake]. 
                     # If you choose fake, the comm_type has no effect. 
                     # Note: now the fake control_type only works for arm control.
    comm_type: uart # Choose one of these:[fake, ethercat, uart]
    joints:
        - &right_wheel right_wheel_joint 
        - &left_wheel left_wheel_joint 
    gear_ratios:
        #- 222.22 
        #- 222.22 
        - 66.7
        - 66.7
# =========== Custom setting stop ============



# You can also modify the followings if you know what you are doing.
#
# for controller spawner
diff_joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

diff_drive_controller:
  type        : "diff_drive_controller/DiffDriveController"
  #right_wheel : 'right_wheel_joint'
  #left_wheel  : 'left_wheel_joint'
  right_wheel : *right_wheel 
  left_wheel  : *left_wheel 
  publish_rate: 50.0               # default: 50
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  #enable_odom_tf: true 

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.38 
  #wheel_separation : 0.129 
  wheel_radius : 0.113
  #wheel_radius : 0.078

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 0.5 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: base_link #default: base_link

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.2  # m/s
      min_velocity           : -0.2 # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.1  # m/s^2
      min_acceleration       : -0.1 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 0.5  # rad/s
      min_velocity           : -0.5  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 0.8  # rad/s^2
      
