# For Hardware Interface
robot:
    n_dof: 3
    update_freq: 1000
    comm_type: ethercat # Choose one of these:[fake, ethercat, uart]
    #joints:
    #- joint1
    #- joint2
    #- joint_eef
    gear_ratios:
        - 1500
        - 1500
        - 1500

